config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for(
    :user,
    {
      class_name: 'Spree::User',
      singular: :spree_user,
      controllers: {
        sessions: 'user_sessions',
        registrations: 'user_registrations',
        passwords: 'user_passwords',
        confirmations: 'user_confirmations'
      },
      skip: %i[unlocks omniauth_callbacks],
      path_names: { sign_out: 'logout' }
    }
  )

  resources :users, only: %i[edit update]

  devise_scope :spree_user do
    get '/login', to: 'user_sessions#new', as: :login
    post '/login', to: 'user_sessions#create', as: :create_new_session
    match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
    get '/signup', to: 'user_registrations#new', as: :signup
    post '/signup', to: 'user_registrations#create', as: :registration
    get '/password/recover', to: 'user_passwords#new', as: :recover_password
    post '/password/recover', to: 'user_passwords#create', as: :reset_password
    get '/password/change', to: 'user_passwords#edit', as: :edit_password
    put '/password/change', to: 'user_passwords#update', as: :update_password
    get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
  end

  resource :account, controller: 'users'

  localized do
    resources :products, only: %i[index show] do
      member do
        post :select_variant
      end

      collection do
        get :filter
        get :search_results
      end
    end
  end

  resources :autocomplete_results, only: :index

  resources :cart_line_items, only: %i[create destroy]

  get '/locale/set', to: 'locale#set'
  post '/locale/set', to: 'locale#set', as: :select_locale

  resource :checkout_session, only: :new
  resource :checkout_guest_session, only: :create

  # non-restful checkout stuff
  patch '/checkout/update/:state', to: 'checkouts#update', as: :update_checkout
  get '/checkout/:state', to: 'checkouts#edit', as: :checkout_state
  get '/checkout', to: 'checkouts#edit', as: :checkout

  get '/orders/:id/token/:token' => 'orders#show', as: :token_order

  resources :orders, only: :show do
    resources :coupon_codes, only: :create
  end

  resource :cart, only: %i[show update] do
    put 'empty'
  end

  # route globbing for pretty nested taxon and product paths
  get '/t/*id', to: 'taxons#show', as: :nested_taxons

  get '/unauthorized', to: 'home#unauthorized', as: :unauthorized
  get '/cart_link', to: 'store#cart_link', as: :cart_link

  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  delete '/orders/:order_id/coupon_codes/:id', to: 'coupon_codes#remove', as: :remove_order_coupon_codes

  localized do
    resources :reparation_categories, only: [:index] do
      resources :reparation_requests, only: %i[new create]
    end
    get 'reparation_requests/thank_you', to: 'reparation_requests#thank_you'
  end

  localized do
    resources :trade_in_requests, only: %i[new create], param: :token
    get 'trade_in_requests/confirmed/:token', to: 'trade_in_requests#show', param: :token, as: :trade_in_request
  end
  get 'trade_in_requests/variant_infos/:variant_id', to: 'trade_in_requests#variant_infos'

  localized do
    get '/account/edit_user_address', to: 'users#edit_user_address'
    get '/account/new_user_address', to: 'users#new_user_address'
  end
  put '/account/update_user_address', to: 'users#update_user_address'

  localized do
    get 'corporate_clients', to: 'home#corporate_clients'
  end
  post 'create_corporate_client_message', to: 'home#create_corporate_client_message'

  localized do
    get 'contact', to: 'home#contact'
    get 'about', to: 'home#about'
    get 'shipping_informations', to: 'home#shipping_informations'
    get 'payment_methods', to: 'home#payment_methods'
    get 'identify_your_model', to: 'home#identify_your_model'
  end
  post 'create_user_message', to: 'home#create_user_message'

  get '/fake_api_call/show_request', to: 'fake_api_calls#show_request'

  # Solidus Routes can't be localized using the localized block...
  # So we have to manually define the routes we want to translate here...
  get '/carrito', to: 'carts#show', as: 'cart_es_mx'
  get '/mi_cuenta', to: 'users#show', as: 'account_es_mx'
  get '/mi_cuenta/editar', to: 'users#edit', as: 'edit_account_es_mx'
  get '/pedidos/:id', to: 'orders#show', as: 'orders_es_mx'

  namespace :repair_shopr_webhook do
    post 'product_updated', to: 'products#product_updated'
  end

  post '/checkout/three_d_secure_response', to: 'checkouts#three_d_secure_response'

  Spree::Core::Engine.routes.draw do
    namespace :admin do
      resources :sync_repair_shopr, only: %i[index new]
      resources :reparation_categories, except: :show
      resources :reparation_requests, only: %i[index show]
      resources :banners, except: :show
      resources :sliders do
        resources :slides
      end
      resources :trade_in_models, only: %i[index] do
        collection do
          get :sync
        end
      end
      resources :trade_in_requests, only: %i[index]

      get '/documentation', to: 'documentation#index'
    end
  end

  # Sidekiq Web UI, only for admins.
  require 'sidekiq/web'
  authenticate :spree_user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/trade_in_request.rb
# frozen_string_literal:true

class TradeInRequest < ApplicationRecord
  belongs_to :variant, class_name: 'Spree::Variant'

  validates :model_name_with_options, :model_min_value, :model_max_value, :shop, :name, :phone, :email, presence: true
  validates :email, format: { with: /\A\S+@\S+\.\S+\z/i }

  enum shop: { bella_vista: 0, san_francisco: 1 }

  before_create :set_with_promo
  before_create :generate_token

  COUPON_VALIDITY_DAYS = 7

  def coupon_code
    "TRADE-IN-#{token[0, 5]}".upcase
  end

  def still_valid?
    return false unless with_promo

    Time.current <= created_at + COUPON_VALIDITY_DAYS.days
  end

  def min_value
    variant&.price.to_f - model_max_value
  end

  def max_value
    variant&.price.to_f - model_min_value
  end

  # TODO: maybe store those addresses somewhere... We are using it in different places of the code
  def shop_address
    case shop
    when 'bella_vista'
      'https://www.google.com/maps/place/Salva+Mi+Maquina+%7C+Bella+Vista/@8.9805139,-79.529011,17z/data=!3m1!4b1!4m5!3m4!1s0x8faca8fb88936ebb:0x56016f2bcd0f178d!8m2!3d8.9805139!4d-79.5268223'
    when 'san_francisco'
      'https://www.google.com/maps/place/Salva+Mi+Maquina+%7C+San+Francisco/@8.9946759,-79.504031,17z/data=!3m1!4b1!4m5!3m4!1s0x8faca91d36aa9129:0x160543d69b5ca01f!8m2!3d8.9947064!4d-79.5018527'
    end
  end

  private

  def set_with_promo
    self.with_promo = !TradeInRequest.exists?(email: email)
  end

  def generate_token
    token = nil
    loop do
      token = SecureRandom.hex(8)

      break unless TradeInRequest.find_by(token: token)
    end

    self.token = token
  end
end

app/controllers/spree/admin/trade_in_requests_controller.rb
# frozen_string_literal:true

module Spree
  module Admin
    class TradeInRequestsController < Spree::Admin::BaseController
      def index
        @trade_in_requests = TradeInRequest.all.order(created_at: :desc).page(params[:page])
      end
    end
  end
end

app/controllers/trade_in_requests_controller.rb
# frozen_string_literal:true

class TradeInRequestsController < StoreController
  def new
    set_form_variables
    @trade_in_request = TradeInRequest.new
    @slider = Slider.find_by(location: :trade_in)
  end

  def create
    @trade_in_request = TradeInRequest.create(trade_in_request_params)
    if @trade_in_request.valid?
      TradeInRequestMailer.confirmation_email(@trade_in_request).deliver_later
      AdminNotificationMailer.trade_in_request_email(@trade_in_request).deliver_later
      redirect_to trade_in_request_path(@trade_in_request.token)
    else
      SendMessageToSentry.send(
        'TradeInRequest error',
        {
          params: trade_in_request_params,
          error: @trade_in_request.errors.messages
        }
      )

      set_form_variables
      @show_fields = true
      render :new, status: :unauthorized
    end
  end

  def show
    @trade_in_request = TradeInRequest.find_by(token: params[:token])
    redirect_to new_trade_in_request_path and return unless @trade_in_request

    @variant = @trade_in_request.variant
    @coupon_validity = TradeInRequest::COUPON_VALIDITY_DAYS
    @coupon_validity_text = "#{@coupon_validity} #{I18n.t('day', count: @coupon_validity).downcase}"
    @shop_name = @trade_in_request.shop.titleize
  end

  def variant_infos
    variant = Spree::Variant.find(params[:variant_id])
    render json: {
      tradeInIsValid: params[:trade_in_max_value].to_f < variant.price,
      name: variant.name,
      price: helpers.number_to_currency(variant.price),
      options: variant.options_text,
      imageTag: helpers.cl_image_tag_with_folder(variant.images.first&.attachment, width: 200, crop: :fill, model: Spree::Image, alt: "#{variant.product.name} - #{variant.options_text}"),
      minValue: helpers.number_to_currency(variant.price - params[:trade_in_max_value].to_f),
      maxValue: helpers.number_to_currency(variant.price - params[:trade_in_min_value].to_f)
    }
  end

  private

  def set_form_variables
    @trade_in_categories = TradeInCategory.all.order(:name)
    @trade_in_models = TradeInModel.all.includes(:trade_in_category).order(:order)
    @accessories_taxon_id = Spree::Taxon.find_by(name: 'Accesorios').id
    @taxons = Spree::Taxon.where.not(id: @accessories_taxon_id).where(depth: 1)
    @products = Spree::Product.includes(:variants, :master, :taxons, :classifications).in_taxons(@taxons).order(:name)
    @variants = Spree::Variant.where(is_master: false, product: @products).includes(:product, [option_values: :option_type]).order(:product_id)
  end

  def trade_in_request_params
    params.require(:trade_in_request).permit(:variant_id, :model_name_with_options, :model_min_value, :model_max_value, :name, :email, :phone, :shop, :comment)
  end
end

app/views/trade_in_requests/new.html.erb
<%= render 'shared/slider', slider: @slider %>

<div id="trade-in-form" class="trade-in">
  <%= simple_form_for @trade_in_request, html: { data: { show_fields: @show_fields, controller: 'trade-in-form' }} do |f| %>
    <div class="trade-in-first-part">
      <h2><%= t('product_you_want_to_trade_in') %></h2>

      <p><%= link_to t('identify_your_model'), identify_your_model_path, target: :blank %></p>
      <div>
        <%=
          select_tag 'trade_in_category_id',
          options_for_select(@trade_in_categories.map { |category| [category.name, category.id] }, params[:trade_in_category_id]),
          prompt: t('choose_product_category'),
          id: 'trade-in-categories'
        %>
      </div>

      <div>
        <!-- Options for the following select tag. Relevant ones will be added to select tag by JS -->
        <div class="options-for-select display-none" data-select-id="trade-in-models">
          <%=
            options_for_select(
              @trade_in_models.map do |model|
                [
                  model.name,
                  model.id,
                  data: {
                    parent_id: model.trade_in_category.id,
                    min_value: model.min_value,
                    max_value: model.max_value,
                    min_value_text: number_to_currency(model.min_value),
                    max_value_text: number_to_currency(model.max_value),
                  }
                ]
              end,
              params[:trade_in_model_id]
            )
          %>
        </div>
        <%=
          select_tag 'trade_in_model_id',
          '', # options will be added by JS
          id: 'trade-in-models',
          class: 'hidden',
          disabled: true,
          data: { prompt: t('choose_product') }
        %>
      </div>

      <div class="trade-in-model-price hidden" data-min-value="" data-max-value="" disabled>
        <input id="trade-in-model-min-value" name="trade_in_request[model_min_value]" hidden>
        <input id="trade-in-model-max-value" name="trade_in_request[model_max_value]" hidden>
        <input id="trade-in-model-name" name="trade_in_request[model_name_with_options]" hidden>
        <p class="model-name-paragraph"><%= t('you_have_a') %> <b class="model-name"></b></p>
        <p class="model-values">(<%= t('estimated_value_between') %> <b class="model-min-value"></b> <%= t('and') %> <b class="model-max-value"></b>) *</p>
      </div>
    </div>

    <div class="trade-in-second-part hidden">
      <div class="trade-in-arrow-separation">
        <%= svg 'arrow_down_circle' %>
      </div>

      <h2><%= t('what_product_you_want_to_buy') %></h2>

      <div>
        <%=
          select_tag 'taxon_id',
          options_for_select(@taxons.map { |taxon| [taxon.name, taxon.id] }, params[:taxon_id]),
          prompt: t('choose_product_category'),
          id: 'taxons',
          disabled: true
        %>
      </div>

      <div>
        <!-- Options for the following select tag. Relevant ones will be added to select tag by JS -->
        <div class="options-for-select display-none" data-select-id="products">
          <%=
            options_for_select(
              @products.map do |product|

                [
                  product.name,
                  product.id,
                  data: {
                    parent_id: product.taxons.first.depth == 2 ? @accessories_taxon_id : product.taxon_ids.first,
                    has_variants: product.has_variants?,
                    master_id: product.master&.id
                  }
                ]
              end,
              params[:product_id]
            )
          %>
        </div>
        <%=
          select_tag 'product_id',
          '', # options will be added by JS
          id: 'products',
          class: 'hidden',
          disabled: true,
          data: { prompt: t('choose_product') }
        %>
      </div>

      <div>
        <!-- Options for the following select tag. Relevant ones will be added to select tag by JS -->
        <div class="options-for-select display-none" data-select-id="variants">
          <%=
            options_for_select(
              @variants.map do |variant|
                [
                  "#{variant.name} - #{variant.options_text}",
                  variant.id,
                  data: { parent_id: variant.product_id }
                ]
              end,
              params[:trade_in_request]&.dig(:variant_id)
            )
          %>
        </div>
        <%=
          select_tag 'trade_in_request[variant_id]',
          '', # options will be added by JS
          id: 'variants',
          class: 'hidden',
          disabled: true,
          data: { prompt: t('choose_variant') }
        %>
      </div>

      <div id="invalid-trade-in" class="display-none centered-flexbox" disabled>
        <div class="">
          <p><%= t('please_choose_product_with_higher_value') %></p>
        </div>
      </div>

      <div class="variant-infos" class="hidden" disabled>
        <div class="variant-price-to-compute centered-flexbox">
          <div>
            <%= t('you_can_by_a') %> <b class="variant-name"><!-- added by JS --></b> - <b class="variant-options"><!-- added by JS --></b>
            <br /><%= t('between') %> <b class="variant-min-price"><!-- added by JS --></b> <%= t('and') %> <b class="variant-max-price"><!-- added by JS --></b>
          </div>
        </div>
        <div class="variant-image"><!-- added by JS --></div>
        <p class="variant-price-container">(<%= t('instead_of') %> <b class="variant-price"><!-- added by JS --></b>)</p>
      </div>
    </div>

    <div id="trade-in-third-part">
      <!-- Button trigger modal -->
      <button id="trade-in-cta" type="button" class="btn btn-primary hidden" data-bs-toggle="modal" data-bs-target="#tradeInFormModal" disabled>
        <%= t('confirm_trade_in_request') %>
      </button>

      <!-- Modal -->
      <div class="modal fade" id="tradeInFormModal" tabindex="-1" aria-labelledby="tradeInFormModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <span><%= t('complete_your_contact_infos') %></span>
              <button type="button" class="btn-close centered-flexbox" data-bs-dismiss="modal" aria-label="Close">
                <%= svg 'cross' %>
              </button>
            </div>
            <div class="modal-body">
              <%= f.input :name, label: false %>
              <%= f.input :email, label: false %>
              <%= f.input :phone, label: false %>
              <%= f.input :comment, label: false %>
              <%= f.input :shop, collection: TradeInRequest.shops.symbolize_keys.keys, include_blank: false %>
              <%= f.submit t('spree.confirm').upcase, class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>

  <% end %>

  <div class="trade-in-disclaimers">
    <p><i>* <%= t('trade_in_disclaimer') %></i></p>
  </div>
</div>

app/views/trade_in_requests/show.html.erb
<div class="trade-in">
  <h2><%= t('trade_in_request_confirmed') %></h2>
  <div
    id="trade-in-promo"
    class="centered-flexbox"
    style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_url('tradein.jpg') %>');"
  >
    <div>
      <% if @trade_in_request.with_promo %>
        <p><%= raw t('complete_trade_in_to_have_a_promo', shop: @shop_name, validity: @coupon_validity_text, amount: '20%') %> **</p>
        <span id="trade-in-coupon-code"><%= @trade_in_request.coupon_code %></span>
        <p>(<%= t('you_have_until', date: I18n.localize((@trade_in_request.created_at + @coupon_validity.days), format: :simple).titleize) %>)</p>
      <% else %>
        <p><%= t('complete_trade_in', shop: @shop_name) %></p>
      <% end %>
        <p id="trade-in-shop-cta">
          <a href="<%= @trade_in_request.shop_address %>" target="_blank">
            <button class="btn btn-secondary">
              <%= t('bring_me_to_shop', shop: @shop_name).upcase %>
            </button>
          </a>
        </p>
    </div>
  </div>

  <hr />

  <div class="trade-in-first-part">
    <h2><%= t('your_trade_in') %></h2>
    <div class="trade-in-model-price">
      <p class="model-name-paragraph">
        <%= t('you_have_a') %> <b class="model-name"><%= @trade_in_request.model_name_with_options %></b>
      </p>
      <p class="model-values">
        (<%= t('estimated_value_between') %> <b class="model-min-value"><%= number_to_currency(@trade_in_request.model_min_value) %></b> <%= t('and') %> <b class="model-max-value"><%= number_to_currency(@trade_in_request.model_max_value) %></b>) *
      </p>
    </div>
  </div>

  <div class="trade-in-second-part">
    <div class="trade-in-arrow-separation">
      <%= svg 'arrow_down_circle' %>
    </div>

    <div class="variant-infos">
      <div class="variant-price-to-compute centered-flexbox">
        <div>
          <%= t('you_can_by_a') %> <b class="variant-name"><%= @variant.name %></b> - <b class="variant-options"><%= @variant.options_text %></b>
          <br />
          <%= t('between') %> <b class="variant-min-price"><%= number_to_currency(@trade_in_request.min_value) %></b> <%= t('and') %> <b class="variant-max-price"><%= number_to_currency(@trade_in_request.max_value) %></b>
        </div>
      </div>
      <div class="variant-image">
        <%= cl_image_tag_with_folder(
          @variant.images.first&.attachment,
          width: 200,
          crop: :fill,
          model: Spree::Image,
          alt: "#{@variant.product.name} - #{@variant.options_text}"
        ) %>
      </div>
      <p>
        <i>(<%= t('instead_of') %> <b class="variant-price"><%= number_to_currency(@variant.price) %></b>)</i>
      </p>
    </div>
  </div>
  <div class="trade-in-disclaimers">
    <p><i>* <%= t('trade_in_disclaimer') %></i></p>
    <p><i>** <%= t('trade_in_promo_restrictiones') %>. <%= t('not_valid_online') %></i></p>
  </div>
</div>