config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for(
    :user,
    {
      class_name: 'Spree::User',
      singular: :spree_user,
      controllers: {
        sessions: 'user_sessions',
        registrations: 'user_registrations',
        passwords: 'user_passwords',
        confirmations: 'user_confirmations'
      },
      skip: %i[unlocks omniauth_callbacks],
      path_names: { sign_out: 'logout' }
    }
  )

  resources :users, only: %i[edit update]

  devise_scope :spree_user do
    get '/login', to: 'user_sessions#new', as: :login
    post '/login', to: 'user_sessions#create', as: :create_new_session
    match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
    get '/signup', to: 'user_registrations#new', as: :signup
    post '/signup', to: 'user_registrations#create', as: :registration
    get '/password/recover', to: 'user_passwords#new', as: :recover_password
    post '/password/recover', to: 'user_passwords#create', as: :reset_password
    get '/password/change', to: 'user_passwords#edit', as: :edit_password
    put '/password/change', to: 'user_passwords#update', as: :update_password
    get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
  end

  resource :account, controller: 'users'

  localized do
    resources :products, only: %i[index show] do
      member do
        post :select_variant
      end

      collection do
        get :filter
        get :search_results
      end
    end
  end

  resources :autocomplete_results, only: :index

  resources :cart_line_items, only: %i[create destroy]

  get '/locale/set', to: 'locale#set'
  post '/locale/set', to: 'locale#set', as: :select_locale

  resource :checkout_session, only: :new
  resource :checkout_guest_session, only: :create

  # non-restful checkout stuff
  patch '/checkout/update/:state', to: 'checkouts#update', as: :update_checkout
  get '/checkout/:state', to: 'checkouts#edit', as: :checkout_state
  get '/checkout', to: 'checkouts#edit', as: :checkout

  get '/orders/:id/token/:token' => 'orders#show', as: :token_order

  resources :orders, only: :show do
    resources :coupon_codes, only: :create
  end

  resource :cart, only: %i[show update] do
    put 'empty'
  end

  # route globbing for pretty nested taxon and product paths
  get '/t/*id', to: 'taxons#show', as: :nested_taxons

  get '/unauthorized', to: 'home#unauthorized', as: :unauthorized
  get '/cart_link', to: 'store#cart_link', as: :cart_link

  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  delete '/orders/:order_id/coupon_codes/:id', to: 'coupon_codes#remove', as: :remove_order_coupon_codes

  localized do
    resources :reparation_categories, only: [:index] do
      resources :reparation_requests, only: %i[new create]
    end
    get 'reparation_requests/thank_you', to: 'reparation_requests#thank_you'
  end

  localized do
    resources :trade_in_requests, only: %i[new create], param: :token
    get 'trade_in_requests/confirmed/:token', to: 'trade_in_requests#show', param: :token, as: :trade_in_request
  end
  get 'trade_in_requests/variant_infos/:variant_id', to: 'trade_in_requests#variant_infos'

  localized do
    get '/account/edit_user_address', to: 'users#edit_user_address'
    get '/account/new_user_address', to: 'users#new_user_address'
  end
  put '/account/update_user_address', to: 'users#update_user_address'

  localized do
    get 'corporate_clients', to: 'home#corporate_clients'
  end
  post 'create_corporate_client_message', to: 'home#create_corporate_client_message'

  localized do
    get 'contact', to: 'home#contact'
    get 'about', to: 'home#about'
    get 'shipping_informations', to: 'home#shipping_informations'
    get 'payment_methods', to: 'home#payment_methods'
    get 'identify_your_model', to: 'home#identify_your_model'
  end
  post 'create_user_message', to: 'home#create_user_message'

  get '/fake_api_call/show_request', to: 'fake_api_calls#show_request'

  # Solidus Routes can't be localized using the localized block...
  # So we have to manually define the routes we want to translate here...
  get '/carrito', to: 'carts#show', as: 'cart_es_mx'
  get '/mi_cuenta', to: 'users#show', as: 'account_es_mx'
  get '/mi_cuenta/editar', to: 'users#edit', as: 'edit_account_es_mx'
  get '/pedidos/:id', to: 'orders#show', as: 'orders_es_mx'

  namespace :repair_shopr_webhook do
    post 'product_updated', to: 'products#product_updated'
  end

  post '/checkout/three_d_secure_response', to: 'checkouts#three_d_secure_response'

  Spree::Core::Engine.routes.draw do
    namespace :admin do
      resources :sync_repair_shopr, only: %i[index new]
      resources :reparation_categories, except: :show
      resources :reparation_requests, only: %i[index show]
      resources :banners, except: :show
      resources :sliders do
        resources :slides
      end
      resources :trade_in_models, only: %i[index] do
        collection do
          get :sync
        end
      end
      resources :trade_in_requests, only: %i[index]

      get '/documentation', to: 'documentation#index'
    end
  end

  # Sidekiq Web UI, only for admins.
  require 'sidekiq/web'
  authenticate :spree_user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < StoreController
  invisible_captcha only: %i[create_user_message create_corporate_client_message], honeypot: :names

  def index
    @products = Spree::Product
                .includes(variants_including_master: [{ images: [attachment_attachment: :blob] }, :prices])
                .where(highlight: true)
                .limit(4)
    @slider = Slider.find_by(location: :home_page)
  end

  def contact
    @user_message = UserMessage.new
    @slider = Slider.find_by(location: :contact)
    generate_business_hours
  end

  def corporate_clients
    @user_message = UserMessage.new
    find_corporate_clients_sliders

    @corporate_services = corporate_services
  end

  def create_user_message
    @user_message = UserMessage.new(user_message_params)
    if @user_message.save
      AdminNotificationMailer.user_message_email(@user_message).deliver_later
      flash.notice = t('message_sent')
      redirect_to contact_path
    else
      generate_business_hours
      render :contact, status: :unauthorized
    end
  end

  def create_corporate_client_message
    @user_message = UserMessage.new(user_message_params)
    if @user_message.save
      AdminNotificationMailer.corporate_message_email(@user_message).deliver_later
      flash.notice = t('message_sent')
      redirect_to corporate_clients_path
    else

      @corporate_services = corporate_services
      find_corporate_clients_sliders
      render :corporate_clients, status: :unauthorized
    end
  end

  def about
    @slider = Slider.find_by(location: :about)
  end

  def shipping_informations
    @shipping_methods = Spree::ShippingMethod.includes(:calculator, zones: [zone_members: :zoneable]).where(service_level: 'delivery').order(:code)
    @stores = Spree::ShippingMethod.where(service_level: nil)
    @free_shipping_threshold = Spree::Promotion::FREE_SHIPPING_THRESHOLD
  end

  def payment_methods; end

  def identify_your_model
    identify_model_links = {
      ipad: 'https://support.apple.com/es-es/HT201471',
      iphone: 'https://support.apple.com/es-es/HT201296',
      mac: 'https://support.apple.com/es-es/HT201581'
    }

    @model_types = %w[iPhone iPad Mac].map do |model_type|
      {
        name: model_type,
        identify_model_link: identify_model_links[model_type.downcase.to_sym]
      }
    end
  end

  private

  def user_message_params
    params.require(:user_message).permit(:name, :email, :message)
  end

  def generate_business_hours
    business_hours = RepairShoprApi::V1::Base.get_business_hours.map do |business_hour|
      business_hour.symbolize_keys!
      unless business_hour[:closed]
        business_hour[:start] = business_hour[:start].to_time.strftime('%I:%M%p')
        business_hour[:end] = business_hour[:end].to_time.strftime('%I:%M%p')
      end
      business_hour
    end

    @business_hours = business_hours.sort_by! { |day| %w[Monday Tuesday Wednesday Thursday Friday Saturday Sunday].index(day[:day]) }
  end

  def find_corporate_clients_sliders
    @slider_1 = Slider.find_by(location: :corporate_clients_1)
    @slider_2 = Slider.find_by(location: :corporate_clients_2)
  end

  # TODO: improve how we deal with this data... Maybe create a CorporateService model?
  def corporate_services
    %w[
      repair
      customer_service
      emergency
      credit
      quality
      delivery
    ]
  end
end

app/views/home/about.html.erb
<%= render 'shared/slider', slider: @slider %>

<div id="about">
  <h1>Sobre Salva Mi Máquina</h1>

  <div id="about-content">
    <%= image_tag 'about-bella-vista.jpg', alt: 'Equipo de la tienda de Bella Vista de Salva Mi Máquina' %>

    <p>Salva Mi Máquina es un empresa panameña <b>creada en enero del 2016</b> por Victor Manche. La idea surgió cuando el cargador de su viejo Macbook Unibody 2008 dejó de funcionar. Se dió cuenta de que no habían opciones económicas, y tampoco buen servicio al cliente para poder solucionar su problema.</p>

    <p>La empresa empezó con la venta de cargadores de Mac económicos y luego comenzó a ofrecer servicio técnico a domicilio.</p>

    <p>Se unió al proyecto Victor Romero en el 2017 como técnico, y ahora es Socio y Director Técnico de la empresa. Finalmente, Quentin Abadie se sumó a la aventura en el 2018 como Director Comercial. Tambien es Gerente de la sucursal de San Francisco.</p>

    <%= image_tag 'about-san-francisco.jpg', alt: 'Equipo de la tienda de San Francisco de Salva Mi Máquina' %>

    <p>Nuestra meta es ofrecer a nuestra clientela la <b>mejor experiencia de servicio técnico, a un costo accesible para todos</b>. Para lograr eso hemos invertido en un <b>amplio y surtido inventario de piezas originales</b> (o de calidad equivalente), para poder diagnosticar y reparar los equipo en el menor tiempo posible. También contamos con el apoyo de <b>12 técnicos divididos entre las sucursales de Bella Vista y San Franciso.</b></p>

    <p>Otro aspeto que nos diferencia de nuesta competencia es que contamos con un <b>taller de reparación de tarjetas madres</b> (placas lógicas), que en la mayoria de los casos nos permite salvar equipos, evitando que el cliente deba reemplazar su equipo o invertir mucho dinero para repararlo.<p>

    <p>Desde el 2019, Salva Mi Máquina también ofrece a sus clientes <b>equipos nuevos con garantía</b>. Mantenemos en stock equipos nuevos para todas las necesidades y gustos y a precios accesibles.</p>
  </div>
</div>

app/views/home/contact.html.erb
<%= render 'shared/slider', slider: @slider %>

<div id="contact">
  <h1 class="text-center"><%= t('contact') %></h1>
  <div id="users-contact-form" class="contact-form centered-flexbox">
    <%= simple_form_for @user_message, url: create_user_message_path do |f| %>
      <%= f.input :name, label: false, placeholder: :name, required: true %>
      <%= f.input :email, label: false, placeholder: :email, required: true %>
      <%= invisible_captcha :names %>
      <%= f.input :message, label: false, placeholder: :message, required: true %>
      <%= f.submit t('send').upcase, class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
  <div id="shops" class="centered-flexbox">
    <div class="shop text-center">
      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d7881.818153459288!2d-79.526822!3d8.980514!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x56016f2bcd0f178d!2sSalva%20Mi%20Maquina%20%7C%20Bella%20Vista!5e0!3m2!1sen!2sus!4v1630921791184!5m2!1sen!2sus" width="450" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
      <h2>Salva Mi Máquina Bella Vista</h2>
      <p>+507 203-2055</p>
    </div>
    <div class="shop text-center">
      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15763.020802214649!2d-79.501836!3d8.994659!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x160543d69b5ca01f!2sSalva%20Mi%20Maquina%20%7C%20San%20Francisco!5e0!3m2!1sen!2sus!4v1630921885655!5m2!1sen!2sus" width="450" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
      <h2>Salva Mi Máquina San Francisco</h2>
      <p>+507 394-9351</p>
    </div>
  </div>
  <div id="business-hours" class="centered-flexbox">
    <div>
      <h2 class="text-center"><%= t('business_hours') %></h2>
      <% @business_hours.each do |business_hour| %>
        <% if business_hour[:closed] %>
          <p><b><span class="business-day"><%= t("#{business_hour[:day].downcase}") %></span></b><%= t('closed') %></p>
        <% else %>
          <p><b><span class="business-day"><%= t("#{business_hour[:day].downcase}") %></span></b><%= business_hour[:start] %> - <%= business_hour[:end] %></p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/corporate_clients.html.erb
<%= render 'shared/slider', slider: @slider_1 %>

<div id="corporate-clients">
  <h1 class="text-center">Servicios a clientes corporativos</h1>

  <div id="corporate-services">
    <% @corporate_services.each do |corporate_service| %>
      <div class="corporate-service">
        <%= svg corporate_service %>
        <h2><%= t("corporate_services.#{corporate_service}.title") %></h2>
        <p><%= t("corporate_services.#{corporate_service}.text") %></p>
      </div>
    <% end %>
  </div>

  <div id="corporate-clients-slider">
    <%= render 'shared/slider', slider: @slider_2, no_fallback: true %>
  </div>

  <div id="corporate-clients-contact">
    <div id="corporate-clients-contact-information">
      <p><b><%= t('contact').upcase %></b></p>
      <p>quentin@salvamimaquina.com</p>
      <p>+507 6822-7135</p>
      <br />
      <p><b><%= t('hour') %></b></p>
      <p><%= t('monday') %> <%= t('to') %> <%= t('friday') %> : 9 am – 7 pm</p>
    </div>
    <div id="corporate-clients-contact-form" class="contact-form">
      <%= simple_form_for @user_message, url: create_corporate_client_message_path(anchor: 'corporate-clients-contact-form') do |f| %>
        <%= invisible_captcha %>
        <%= f.input :name, label: false, placeholder: :name %>
        <%= f.input :email, label: false, placeholder: :email, required: true %>
        <%= f.input :message, label: false, placeholder: :message, required: true %>
        <%= f.submit t('send').upcase, class: 'btn btn-primary w-100' %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/identify_your_model.html.erb
<div id="identify-your-model" class="container">
  <h1><%= t('identify_the_model_of_your_product') %></h1>

  <div class="model-types">
    <% @model_types.each do |model_type| %>
      <div class="model-type">
        <h2><%= t('you_have_an', model_type: model_type[:name]) %></h2>
        <%= image_tag "#{model_type[:name].downcase}.png", width: 300 %>
        <p><%= t('find_what_model_you_have', model_type: model_type[:name]) %></p>
        <a href="<%= model_type[:identify_model_link] %>" target="_blank" class="full-absolute"></a>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'shared/slider', slider: @slider %>
<div id="homepage-intro">
  <h1><%= t('home_page.intro_title') %></h1>
  <p><%= t('home_page.intro') %></p>
</div>
<div class="homepage-block">
  <h2 class="homepage-title"><%= t('home_page.reparation_service_title').upcase %></h2>
  <div class="homepage-features">
    <div class="homepage-feature">
      <%= svg 'journal' %>
      <h3 class="homepage-feature-title"><%= t('home_page.features.feature_one_title') %></h3>
      <p><%= t('home_page.features.feature_one_text') %></p>
    </div>
    <div class="homepage-feature">
      <%= svg 'shop' %>
      <h3 class="homepage-feature-title"><%= t('home_page.features.feature_two_title') %></h3>
      <p><%= t('home_page..features.feature_two_text') %></p>
    </div>
    <div class="homepage-feature">
      <%= svg 'emoji_smile' %>
      <h3 class="homepage-feature-title"><%= t('home_page.features.feature_three_title') %></h3>
      <p><%= t('home_page.features.feature_three_text') %></p>
    </div>
  </div>
  <div class="centered-flexbox">
    <%= link_to t('reparation'), reparation_categories_path, class: 'btn btn-primary rounded large' %>
  </div>
</div>
<% if @products.any? %>
  <div class="homepage-block" data-hook="homepage_products">
    <h2 class="homepage-title"><%= t('home_page.shop_name').upcase %></h2>
    <h3 class="homepage-subtitle"><%= t('home_page.best_at_best_price') %></h3>
    <%= render 'shared/products', products: @products %>
  </div>
<% end %>

app/views/home/payment_methods.html.erb
<div id="payment-methods">
  <div class="payment-methods-block">
    <h3><%= t('spree.payment_methods.credit_card') %></h3>
    <div id="payment-methods">
      <div class="payment-method">
        <p><b>Visa</b></p>
        <%= svg 'visa' %>
      </div>
      <div class="payment-method">
        <p><b>Master Card</b></p>
        <%= svg 'master' %>
      </div>
    </div>
  </div>
</div>

app/views/home/shipping_informations.html.erb
<div id="shipping-informations">
  <div class="shipping-informations-block">
    <h3><%= t('spree.shipping_prices') %></h3>
    <div id="shipping-methods">
      <% @shipping_methods.each do |shipping_method| %>
        <div class="shipping-method">
          <p><b><%= t("spree.shipping_methods.#{shipping_method.admin_name}") %></b></p>
          <p class="shipping-price"><%= number_to_currency(shipping_method.calculator.preferences[:amount]) %></p>
          <% if [1, 2].include?(shipping_method.code.to_i) %>
            <p class="free-shipping">
              <%= t('spree.free_shipping_for_orders_above_threshold', free_shipping_threshold: number_to_currency(@free_shipping_threshold)) %>
            </p>
          <% end %>
          <p><span class="district"><%= t('spree.district', count: 2) %>:</span> <%= shipping_method.zones.first.members.map(&:name).sort.join(', ') %></p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="shipping-informations-block" id="pickup-in-stores">
    <h3><%= t('spree.pickup_in_stores') %> (gratis)</h3>
    <ul>
      <% @stores.each do |store| %>
        <li>
          <%= t('spree.shipping_methods.pickup_in_store', store_name: store.admin_name) %>: <%= link_to t('spree.address').downcase, "http://www.google.com/maps/place/#{store.latitude},#{store.longitude}", target: '_blank' %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="shipping-informations-block">
    <h3><%= t('spree.shipping_times') %></h3>
    <span><%= t('spree.between_1_and_3_days') %></span>
  </div>
</div>